#!/usr/bin/env python3
"""Export CLean proofs to Rob's ingestion shape: a property graph (neo4j) + a
vector table (pgvector). Locally we emit the artifacts; the generated cypher/SQL
ARE the documented contract for his stack.

Mapping (extends the E-clean table):
  CLean                         neo4j                         pgvector
  -----                         -----                         --------
  :clean/proof                  (:Proof {id,title,macro})     row key
  :clean/boxes[]                (:Step {method,text,...})     —
  :clean/wires[]                (:Step)-[:WIRES{carries}]->   —
  :hole {satiety,discharge}     Step props has_hole/satiety   —
  :discharges {:to}             (:Step)-[:DISCHARGES_TO]->    —
                                  (:Theorem {name})
  structure embedding           —                             structure vector(33)
  text embedding                —                             text_emb vector(D)

Outputs (default data/showcases/clean-demo/ingest/):
  clean-graph.json   one combined property graph (all proofs)
  load.cypher        neo4j loader producing that graph
  pgvector.sql       table + inserts + a sample structure-ANN query
"""
import argparse
import glob
import json
import os
import numpy as np
import edn_format as edn

# reuse the loader helpers from the embedder
from clean_structure_embed import kw, load_clean, boxes_of, wires_of


def cypher_str(s):
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'") + "'"


def build(clean_dir, out, embed_json):
    files = sorted(glob.glob(os.path.join(clean_dir, "*.clean.edn")))
    payload = json.load(open(embed_json)) if os.path.exists(embed_json) else None

    graph = {"nodes": [], "edges": []}
    cypher = ["// CLean -> neo4j loader (generated by clean_graph_export.py)",
              "// run: cypher-shell < load.cypher",
              "CREATE CONSTRAINT proof_id IF NOT EXISTS FOR (p:Proof) REQUIRE p.id IS UNIQUE;",
              "CREATE CONSTRAINT step_id IF NOT EXISTS FOR (s:Step) REQUIRE s.id IS UNIQUE;",
              ""]
    theorems = set()

    for f in files:
        d = load_clean(f)
        pid = kw(d["proof"])
        title = str(d.get("title", ""))
        shape = {kw(k): v for k, v in dict(d["shape"]).items()}
        macro = kw(shape["macro"])
        boxes = boxes_of(d)
        wires = wires_of(d)

        graph["nodes"].append({"label": "Proof", "id": pid, "title": title, "macro": macro})
        cypher.append(f"MERGE (p_{pid}:Proof {{id:{cypher_str(pid)}}}) "
                      f"SET p_{pid}.title={cypher_str(title)}, p_{pid}.macro={cypher_str(macro)};")

        for b in boxes:
            sid = f"{pid}/{b['id']}"
            node = {"label": "Step", "id": sid, "proof": pid, "method": b["method"],
                    "text": b["text"], "has_hole": "hole" in b}
            if "hole" in b:
                node["satiety"] = b["hole"]["satiety"]
                node["discharge"] = b["hole"]["discharge"]
            graph["nodes"].append(node)
            var = f"s_{pid}_{b['id']}"
            props = (f"{{id:{cypher_str(sid)}, proof:{cypher_str(pid)}, "
                     f"method:{cypher_str(b['method'])}, text:{cypher_str(b['text'])}, "
                     f"has_hole:{str('hole' in b).lower()}")
            if "hole" in b:
                props += f", satiety:{cypher_str(b['hole']['satiety'])}, discharge:{cypher_str(b['hole']['discharge'])}"
            props += "}"
            cypher.append(f"MERGE ({var}:Step {props});")
            cypher.append(f"MERGE (p_{pid})-[:HAS_STEP]->({var});")
            if "discharges" in b:
                thm = b["discharges"]["to"]
                theorems.add(thm)
                graph["edges"].append({"type": "DISCHARGES_TO", "from": sid, "to": thm})
                cypher.append(f"MERGE (t_{thm.replace('-', '_')}:Theorem {{name:{cypher_str(thm)}}});")
                cypher.append(f"MERGE ({var})-[:DISCHARGES_TO]->(t_{thm.replace('-', '_')});")

        for w in wires:
            graph["edges"].append({"type": "WIRES", "from": f"{pid}/{w['from']}",
                                   "to": f"{pid}/{w['to']}", "carries": w["carries"]})
            cypher.append(f"MERGE (s_{pid}_{w['from']})-[:WIRES {{carries:{cypher_str(w['carries'])}}}]->(s_{pid}_{w['to']});")
        cypher.append("")

    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "clean-graph.json"), "w") as fh:
        json.dump(graph, fh, indent=2)
    with open(os.path.join(out, "load.cypher"), "w") as fh:
        fh.write("\n".join(cypher))

    # ---- pgvector ----
    sql = ["-- CLean structure + text embeddings -> pgvector (generated)",
           "CREATE EXTENSION IF NOT EXISTS vector;",
           "DROP TABLE IF EXISTS clean_proof;"]
    if payload:
        sdim, tdim = payload["structure_dim"], payload["text_dim"]
        S = np.load(os.path.join(os.path.dirname(embed_json), "structure-embeddings.npy"))
        T = np.load(os.path.join(os.path.dirname(embed_json), "text-embeddings.npy"))
        sql.append(f"CREATE TABLE clean_proof (id text PRIMARY KEY, title text, macro text, "
                   f"structure vector({sdim}), text_emb vector({tdim}));")
        for i, pid in enumerate(payload["ids"]):
            sv = "[" + ",".join(f"{x:.6f}" for x in S[i]) + "]"
            tv = "[" + ",".join(f"{x:.6f}" for x in T[i]) + "]"
            sql.append(f"INSERT INTO clean_proof VALUES ({cypher_str(pid)}, "
                       f"{cypher_str(payload['titles'][i])}, {cypher_str(payload['macros'][i])}, "
                       f"'{sv}', '{tv}');")
        sql += [
            "",
            "-- structure-ANN: nearest proofs to b97J01 by COMB SHAPE (cosine).",
            "-- The point: this returns t94A07 (topology) as the #1 structural twin of",
            "-- a group-theory proof -- a match text embeddings (text_emb) do not make.",
            "SELECT id, macro, round((1 - (structure <=> "
            "(SELECT structure FROM clean_proof WHERE id='b97J01')))::numeric, 4) AS struct_sim",
            "FROM clean_proof WHERE id <> 'b97J01' ORDER BY structure <=> "
            "(SELECT structure FROM clean_proof WHERE id='b97J01') LIMIT 3;",
            "",
            "-- contrast: same query over TEXT embeddings scatters the twin.",
            "SELECT id, macro, round((1 - (text_emb <=> "
            "(SELECT text_emb FROM clean_proof WHERE id='b97J01')))::numeric, 4) AS text_sim",
            "FROM clean_proof WHERE id <> 'b97J01' ORDER BY text_emb <=> "
            "(SELECT text_emb FROM clean_proof WHERE id='b97J01') LIMIT 3;",
        ]
    with open(os.path.join(out, "pgvector.sql"), "w") as fh:
        fh.write("\n".join(sql))

    print(f"graph: {len(graph['nodes'])} nodes, {len(graph['edges'])} edges, {len(theorems)} theorems")
    print(f"wrote {out}/clean-graph.json, load.cypher, pgvector.sql")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--clean-dir", default="holes/clean")
    ap.add_argument("--out", default="data/showcases/clean-demo/ingest")
    ap.add_argument("--embed-json", default="data/showcases/clean-demo/clean-embed.json")
    args = ap.parse_args()
    build(args.clean_dir, args.out, args.embed_json)


if __name__ == "__main__":
    main()
