#!/usr/bin/env python3
"""CLean -> DarkTower Lean emitter (deterministic).

Renders a CLean EDN proof to the DarkTower Lean types, exactly as
`mathlib4/DarkTower/Examples.lean` instantiates the mission sketch
(`MissionExample`). The render IS the correctness gate: a CLean is well-formed
iff it produces type-correct, 0-sorry DarkTower Lean.

Each proof becomes a namespace with:
  - `inductive Method`     the distinct iching/CT method tags in the spine
  - `def spine : BV Method`    the pattern-tagged method spine (informal reading)
  - `inductive Stp`        the proof steps (comb positions)
  - `inductive Obligation` the direction a still-open hole exposes (a proof)
  - `def holes : TypedHole` poly positions = steps; B step = Obligation if the
                            step has a typed hole, else Empty (discharged);
                            satiety from the CLean hole grade
  - `def discharges`       reduce-to-known steps -> named theorems
  - `def wires`            the comb edges (construct -> consume), as data
  - `def readings : BV Reading`  the informal ∥ formal copar
  - self-verifying `example`s (holeType / satiety / discharge / BV reassoc) that
    all close by rfl/decide -> 0 sorry.

Two modes:
  --mode real        import Mathlib + DarkTower modules; lands in the repo
                     (compiles once mathlib oleans are built).
  --mode standalone  prepend a minimal shim of the exact DarkTower signatures
                     the render touches; compiles NOW with core `lean` (no
                     mathlib), giving a real 0-sorry check.

Usage:
  futon6/.venv/bin/python scripts/clean_to_lean.py \
      --clean-dir holes/clean --mode real \
      --out /home/joe/code/mathlib4/DarkTower/CLeanProofs.lean
  futon6/.venv/bin/python scripts/clean_to_lean.py --mode standalone \
      --out /tmp/clean_lean_check.lean
  futon6/.venv/bin/python scripts/clean_to_lean.py --kind experiment \
      --only slice5-confirmation --mode real \
      --out /home/joe/code/mathlib4/DarkTower/CLeanSlice5Confirmation.lean
"""
import argparse
import glob
import os
import re
from clean_structure_embed import kw, load_clean, boxes_of, wires_of


def camel(s):
    parts = s.replace("/", "-").split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


SHIM = r"""-- Minimal shim of the DarkTower signatures the CLean render touches.
-- Signature-identical to mathlib4/DarkTower/{BV,TypedHole,Discharge}.lean, but
-- with no `import Mathlib`, so this file compiles with core `lean`. The real
-- emit (--mode real) targets the Mathlib-backed modules instead.
universe u v
namespace DarkTower

inductive BV (A : Type u) where
  | unit | atom : A -> BV A | seq : BV A -> BV A -> BV A
  | copar : BV A -> BV A -> BV A | par : BV A -> BV A -> BV A
namespace BV
inductive Cong {A : Type u} : BV A -> BV A -> Prop where
  | seq_assoc (S T U : BV A) : Cong (seq (seq S T) U) (seq S (seq T U))
  | copar_comm (S T : BV A) : Cong (copar S T) (copar T S)
end BV

inductive SatietyGrade | parse | payoff | canon | bundling | role
  deriving DecidableEq, Repr
inductive DischargeKind | sorryProof | queryAnswer | ungroundedBinder
  deriving DecidableEq, Repr

structure PFunctor where
  A : Type u
  B : A -> Type v
structure TypedHole where
  poly : PFunctor
  satiety : poly.A -> SatietyGrade
namespace TypedHole
def holeType (T : TypedHole) (a : T.poly.A) : Type v := T.poly.B a
end TypedHole

end DarkTower
"""

REAL_HEADER = """import Mathlib
import DarkTower.TypedHole
import DarkTower.Comb
import DarkTower.Discharge
import DarkTower.BV

/-!
# CLean proofs as DarkTower typed-hole interfaces

Generated by `futon6/scripts/clean_to_lean.py` from `futon6/holes/clean/*.clean.edn`.
Each namespace is the CT treatment of one APM proof, rendered to the same
`BV` / `TypedHole` / `DischargeKind` machinery that types `MissionExample` in
`Examples.lean`. The render is the correctness gate: it builds 0-sorry iff the
CLean is well-formed. See `futon6/holes/excursions/E-clean.md`.
-/
"""

EXPERIMENT_HEADER = """import Mathlib
import DarkTower.TypedHole
import DarkTower.Comb
import DarkTower.Discharge
import DarkTower.BV
import DarkTower.ExperimentPreregistration
import DarkTower.ExperimentalDesign

/-!
# CLean experiments as prospective DarkTower registrations

Generated by `futon6/scripts/clean_to_lean.py` from an experiment-shaped CLean
EDN. The EDN is the authority: axes, arms, complete seed triples, stop rules,
and the total decision function below are all rendered from it.
-/
"""


def plain_map(value):
    """Convert one EDN map to a string-keyed Python dict."""
    return {kw(k): v for k, v in dict(value).items()}


def lean_string(value):
    """Quote a string as a Lean string literal."""
    return '"' + str(value).replace('\\', '\\\\').replace('"', '\\"') + '"'


def lean_num(value):
    """Render the numeric EDN values used by experiment registrations."""
    return str(value)


FORMULA_RE = re.compile(
    r"^\s*(\d+)\s*\+\s*(\d+)\s*\*\s*s\s*\+\s*(?:(\d+)\s*\*\s*)?i\s*$"
)


def parse_seed_formula(text, field):
    """Parse the deliberately tiny experiment seed-formula language."""
    match = FORMULA_RE.fullmatch(str(text))
    if not match:
        raise ValueError(
            f"{field} must have form BASE + STRIDE*s + COEFF*i; got {text!r}"
        )
    base, stride, coeff = match.groups()
    return int(base), int(stride), int(coeff or 1)


def seed_rows(seed_spec, scenarios, default_runs=None):
    spec = plain_map(seed_spec)
    runs = int(spec.get("runs-per-cell", default_runs or 0))
    if runs <= 0:
        raise ValueError("seed plan requires positive :runs-per-cell")
    formulas = {
        name: parse_seed_formula(spec[f"{name}-fn"], f":{name}-fn")
        for name in ("food", "movement", "choice")
    }
    rows = []
    for scenario_index, scenario in enumerate(scenarios):
        for run_index in range(runs):
            values = {}
            for name, (base, stride, coeff) in formulas.items():
                values[name] = base + stride * scenario_index + coeff * run_index
            rows.append((scenario, run_index + 1,
                         values["food"], values["movement"], values["choice"]))
    return rows


def validate_experiment(d):
    """Refuse experiment designs that would turn the navigability gate into a tag."""
    if not str(d.get("title", "")).strip():
        raise ValueError("experiment requires a non-empty :clean/title")
    if kw(d.get("status")) != "registered-not-run":
        raise ValueError("experiment must be :registered-not-run before rendering")
    design = plain_map(d.get("experiment-design") or {})
    axes = [plain_map(axis) for axis in design.get("axes", [])]
    arms = [plain_map(arm) for arm in design.get("arms", [])]
    if not axes or not arms:
        raise ValueError("experiment requires non-empty :axes and :arms")
    axis_by_id = {}
    for axis in axes:
        axis_id = kw(axis.get("id"))
        if not axis_id or axis_id in axis_by_id:
            raise ValueError(f"axis ids must be non-empty and unique: {axis_id!r}")
        levels = list(axis.get("levels", []))
        if len(levels) < 2:
            raise ValueError(f"axis :{axis_id} requires at least two reachable levels")
        varies = bool(axis.get("score-varies?"))
        if varies and not any(x != y for x, y in zip(levels, levels[1:])):
            raise ValueError(
                f"axis :{axis_id} says :score-varies? true but adjacent levels do not vary"
            )
        axis_by_id[axis_id] = axis

    positive_arms = [arm for arm in arms if kw(arm.get("role")) == "positive-control"]
    positive_axes = [axis for axis in axes if kw(axis.get("role")) == "positive-control"]
    if len(positive_arms) > 1 or len(positive_axes) > 1:
        raise ValueError("at most one positive-control arm and axis are permitted")
    if len(positive_arms) != len(positive_axes):
        raise ValueError("positive-control arm and axis must be declared together")

    for arm in arms:
        arm_id = kw(arm.get("id"))
        ablates = [kw(axis_id) for axis_id in arm.get("ablates", [])]
        missing = [axis_id for axis_id in ablates if axis_id not in axis_by_id]
        if missing:
            raise ValueError(f"arm :{arm_id} references unknown axes: {missing}")
        dead = [axis_id for axis_id in ablates
                if not bool(axis_by_id[axis_id].get("score-varies?"))]
        is_positive = kw(arm.get("role")) == "positive-control"
        if dead and not is_positive:
            raise ValueError(
                f"non-navigable treatment refused: arm :{arm_id} ablates "
                f"{', '.join(':' + axis_id for axis_id in dead)} without "
                ":role :positive-control"
            )
        if is_positive:
            if len(ablates) != 1 or dead != ablates:
                raise ValueError(
                    f"positive-control arm :{arm_id} must ablate exactly one non-navigable axis"
                )
            axis = axis_by_id[ablates[0]]
            if kw(axis.get("role")) != "positive-control":
                raise ValueError("positive-control arm must reference the positive-control axis")
            if not str(axis.get("justification", "")).strip():
                raise ValueError("positive-control axis requires a non-empty justification")

    stop_rules = list(design.get("stop-rules", []))
    if not stop_rules:
        raise ValueError("ProspectiveRegistration requires at least one stop rule")
    decision = plain_map(design.get("decision") or {})
    if not decision:
        raise ValueError("ProspectiveRegistration requires a total decision table")
    seeds = plain_map(design.get("seeds") or {})
    stage = kw(seeds.get("stage"))
    if stage not in {"pilot", "confirmation"}:
        raise ValueError("replication plan requires :stage :pilot or :confirmation")
    predecessor = seeds.get("predecessor")
    if stage == "pilot" and predecessor is not None:
        raise ValueError("pilot replication plan must have :predecessor nil")
    if stage == "confirmation" and not str(predecessor or "").strip():
        raise ValueError("confirmation replication plan requires a non-nil :predecessor")

    seedable = seeds.get("seedable?")
    if not isinstance(seedable, bool):
        raise ValueError("replication plan requires boolean :seedable?")
    variation = kw(seeds.get("variation"))
    if seedable:
        if variation != "controlled":
            raise ValueError("seedable replication requires :variation :controlled")
        endpoint = seeds.get("reproducibility-endpoint")
        if not str(endpoint or "").strip():
            raise ValueError(
                "controlled variation requires a named :reproducibility-endpoint"
            )
    else:
        if variation != "measured":
            raise ValueError("non-seedable replication requires :variation :measured")
        endpoint = seeds.get("floor-endpoint")
        if not str(endpoint or "").strip():
            raise ValueError(
                "measured variation requires a named :floor-endpoint"
            )

    scenarios = [kw(s) for s in design.get("scenarios", [])]
    if not scenarios:
        raise ValueError("experiment requires at least one scenario")
    problem_units = []
    predecessor_units = []
    if not seedable:
        problem_units = scenarios
        if stage == "confirmation":
            predecessor_units = [kw(unit) for unit in seeds.get("predecessor-units", [])]
            if not predecessor_units:
                raise ValueError(
                    "non-seedable confirmation requires nonempty :predecessor-units"
                )
            overlap = sorted(set(problem_units) & set(predecessor_units))
            if overlap:
                raise ValueError(
                    f"predecessor and confirmation problem units overlap: {overlap[:5]}"
                )
        pilot_rows = []
        confirmation_rows = []
    elif stage == "confirmation":
        if not bool(seeds.get("disjoint-from-pilot?")):
            raise ValueError("confirmation seed plan must assert :disjoint-from-pilot? true")
        if "pilot" not in seeds:
            raise ValueError("confirmation seed plan must carry structured :pilot formulas")
        pilot_rows = seed_rows(seeds["pilot"], scenarios, seeds.get("runs-per-cell"))
        confirmation_rows = seed_rows(seeds, scenarios)
    else:
        pilot_rows = seed_rows(seeds, scenarios)
        confirmation_rows = []
    prior_confirmation = seeds.get("prior-confirmation") if seedable else None
    prior_confirmation_rows = (
        seed_rows(prior_confirmation, scenarios, seeds.get("runs-per-cell"))
        if prior_confirmation is not None else []
    )
    pilot_ids = {row[2] for row in pilot_rows}
    confirmation_ids = {row[2] for row in confirmation_rows}
    if len(pilot_ids) != len(pilot_rows) or len(confirmation_ids) != len(confirmation_rows):
        raise ValueError("food seeds must uniquely identify registered replicate triples")
    overlap = sorted(pilot_ids & confirmation_ids)
    if overlap:
        raise ValueError(f"pilot and confirmation seeds overlap: {overlap[:5]}")
    if prior_confirmation is not None:
        if not bool(seeds.get("disjoint-from-prior-confirmation?")):
            raise ValueError(
                "seed plan must assert :disjoint-from-prior-confirmation? true"
            )
        prior_ids = {row[2] for row in prior_confirmation_rows}
        overlap = sorted(prior_ids & confirmation_ids)
        if overlap:
            raise ValueError(
                f"prior-confirmation and new seeds overlap: {overlap[:5]}"
            )
    preconditions = plain_map(design.get("preconditions") or {})
    if preconditions:
        necessity = plain_map(preconditions.get("mechanism-necessary") or {})
        delivery = plain_map(preconditions.get("mechanism-delivered") or {})
        if not list(necessity.get("alternative-paths", [])):
            raise ValueError(
                "mechanism-necessary precondition must enumerate alternative paths"
            )
        if not delivery.get("unit") or not delivery.get("check"):
            raise ValueError(
                "mechanism-delivered precondition requires :unit and :check"
            )
    budget = plain_map(design.get("budget") or {})
    if not str(budget.get("teardown", "")).strip():
        raise ValueError("budget requires a non-empty teardown commitment")
    if int(budget.get("estimated-cell-runs", -1)) > int(budget.get("cap-cell-runs", -1)):
        raise ValueError("estimated cell-runs exceed the registered cap")
    return (design, axes, arms, scenarios, pilot_rows, confirmation_rows,
            prior_confirmation_rows, decision, stage, predecessor, variation,
            endpoint, seedable, problem_units, predecessor_units)


def emit_experiment(d):
    """Render an experiment-shaped CLean to the existing DarkTower structures."""
    (design, axes, arms, scenarios, pilot_rows, confirmation_rows,
     prior_confirmation_rows, decision, stage, predecessor, variation,
     endpoint, seedable, problem_units, predecessor_units) = validate_experiment(d)
    eid = kw(d["experiment"])
    ns = f"CLeanExperiment_{eid.replace('-', '_')}"
    axis_names = {kw(axis["id"]): camel(kw(axis["id"])) + "Axis" for axis in axes}
    arm_names = {kw(arm["id"]): camel(kw(arm["id"])) + "Arm" for arm in arms}
    L = []
    a = L.append
    a(f"namespace {ns}")
    a(f"-- {eid}: {d.get('title', '')}")
    a("")
    a("open ExperimentPreregistration")
    a("open ExperimentalDesign")
    a("")

    a("inductive Scenario where")
    for scenario in scenarios:
        a(f"  | {camel(scenario)}")
    a("  deriving DecidableEq, Repr")
    a("")
    if seedable:
        a("structure SeedTriple where")
        a("  scenario : Scenario")
        a("  run : Nat")
        a("  food : Nat")
        a("  movement : Nat")
        a("  choice : Nat")
        a("  deriving DecidableEq, Repr")
        a("")

    def emit_rows(name, rows):
        a(f"def {name} : List SeedTriple := [")
        for index, (scenario, run, food, movement, choice) in enumerate(rows):
            comma = "," if index + 1 < len(rows) else ""
            a("  { scenario := Scenario.%s, run := %d, food := %d, movement := %d, choice := %d }%s" %
              (camel(scenario), run, food, movement, choice, comma))
        a("]")
        a("")

    if seedable:
        emit_rows("pilotSeedTriples", pilot_rows)
        emit_rows("confirmationSeedTriples", confirmation_rows)
        if prior_confirmation_rows:
            emit_rows("priorConfirmationSeedTriples", prior_confirmation_rows)

    for axis in axes:
        axis_id = kw(axis["id"])
        name = axis_names[axis_id]
        levels = ", ".join(lean_num(level) for level in axis["levels"])
        varies = bool(axis.get("score-varies?"))
        a(f"/-- {str(axis.get('justification', '')).replace('-/', '- /')} -/")
        a(f"noncomputable def {name} : Axis where")
        a(f"  name := {lean_string(axis_id)}")
        a(f"  levels := [{levels}]")
        a(f"  score := {'fun x => x' if varies else 'fun _ => 0'}")
        a("")
        if varies:
            a(f"theorem {name}_navigable : {name}.Navigable := by")
            a(f"  norm_num [Axis.Navigable, Axis.gradientSteps, {name}]")
        else:
            a(f"theorem {name}_predicted_not_navigable : ¬ {name}.Navigable :=")
            a("  not_navigable_of_constant (fun _ _ => rfl)")
        a("")

    for arm in arms:
        arm_id = kw(arm["id"])
        axes_expr = ", ".join(axis_names[kw(x)] for x in arm.get("ablates", []))
        source_role = kw(arm.get("role"))
        lean_role = {
            "positive-control": "ArmRole.positiveControl",
            "baseline": "ArmRole.baselineNeutral",
        }.get(source_role, "ArmRole.treatment")
        a(f"noncomputable def {arm_names[arm_id]} : Arm where")
        a(f"  name := {lean_string(arm_id)}")
        a(f"  neutral := {str(bool(arm.get('neutral?'))).lower()}")
        a(f"  axes := [{axes_expr}]")
        a(f"  role := {lean_role}")
        a("")

    trace_classes = [camel(key) for key in decision]
    outcome_ids = []
    for value in decision.values():
        outcome = camel(kw(value))
        if outcome not in outcome_ids:
            outcome_ids.append(outcome)
    a("inductive TraceClass where")
    for trace_class in trace_classes:
        a(f"  | {trace_class}")
    a("  deriving DecidableEq, Repr")
    a("")
    a("inductive Outcome where")
    for outcome in outcome_ids:
        a(f"  | {outcome}")
    a("  deriving DecidableEq, Repr")
    a("")
    a("structure ExperimentTrace where")
    a("  classification : TraceClass")
    a("  positiveControlViolated : Bool")
    a("  deriving Repr")
    a("")

    stop_rules = [plain_map(rule) for rule in design["stop-rules"]]
    for index, rule in enumerate(stop_rules):
        rule_name = camel(kw(rule["id"])) + "Stop"
        if index > 0:
            raise ValueError("current Trace ABI supports exactly one positive-control stop rule")
        if kw(rule.get("comparison")) != "full-run-record":
            raise ValueError("stop rule comparison must be :full-run-record")
        a(f"def {rule_name} : StopRule ExperimentTrace where")
        a(f"  name := {lean_string(kw(rule['id']))}")
        a("  fires := fun trace => trace.positiveControlViolated = true")
        a("  check := fun trace => trace.positiveControlViolated")
        a("  check_iff := fun _ => Iff.rfl")
        a("")
    stop_name = camel(kw(stop_rules[0]["id"])) + "Stop"

    a("def decisionRule : DecisionRule ExperimentTrace Outcome where")
    a(f"  name := {lean_string(eid + '-decision')}")
    a("  classify := fun trace => match trace.classification with")
    for key, value in decision.items():
        a(f"    | TraceClass.{camel(key)} => Outcome.{camel(kw(value))}")
    a("")

    seed_spec = plain_map(design["seeds"])
    endpoint_kind = "controlled" if variation == "controlled" else "measured"
    endpoint_name = ("reproducibilityEndpoint" if variation == "controlled"
                     else "identityFloorEndpoint")
    a(f"def {endpoint_name} : NamedEndpoint where")
    a(f"  name := {lean_string(kw(endpoint))}")
    a("  nameNonempty := by decide")
    a("")
    if stage == "confirmation":
        a("def predecessorEndpoint : NamedEndpoint where")
        a(f"  name := {lean_string(str(predecessor))}")
        a("  nameNonempty := by decide")
        a("")

    if seedable:
        pilot_spec = plain_map(seed_spec["pilot"] if stage == "confirmation" else seed_spec)
        pilot_base, pilot_stride, pilot_coeff = parse_seed_formula(
            pilot_spec["food-fn"], ":pilot/:food-fn"
        )
        pilot_runs = int(pilot_spec.get("runs-per-cell", seed_spec["runs-per-cell"]))
        a("def pilotUnitIds : List Nat :=")
        a(f"  (List.range {len(scenarios)}).flatMap (fun s =>")
        a(f"    (List.range {pilot_runs}).map (fun i =>")
        a(f"      {pilot_base} + {pilot_stride} * s + {pilot_coeff} * i))")
        a("")
        if stage == "confirmation":
            confirmation_base, confirmation_stride, confirmation_coeff = parse_seed_formula(
                seed_spec["food-fn"], ":food-fn"
            )
            confirmation_runs = int(seed_spec["runs-per-cell"])
            a("def confirmationUnitIds : List Nat :=")
            a(f"  (List.range {len(scenarios)}).flatMap (fun s =>")
            a(f"    (List.range {confirmation_runs}).map (fun i =>")
            a(f"      {confirmation_base} + {confirmation_stride} * s + {confirmation_coeff} * i))")
            a("")
            a("theorem unitIds_disjoint : pilotUnitIds.Disjoint confirmationUnitIds := by")
            a("  rw [List.disjoint_left]")
            a("  intro x hp hc")
            a("  simp only [pilotUnitIds, List.mem_flatMap] at hp")
            a("  rcases hp with ⟨s, hs, hp⟩")
            a("  simp only [List.mem_map] at hp")
            a("  rcases hp with ⟨i, hi, rfl⟩")
            a("  simp only [confirmationUnitIds, List.mem_flatMap] at hc")
            a("  rcases hc with ⟨s', hs', hc⟩")
            a("  simp only [List.mem_map] at hc")
            a("  rcases hc with ⟨i', hi', heq⟩")
            a("  have hs_lt := List.mem_range.mp hs")
            a("  have hi_lt := List.mem_range.mp hi")
            a("  have hs'_lt := List.mem_range.mp hs'")
            a("  have hi'_lt := List.mem_range.mp hi'")
            a("  omega")
            a("")
    else:
        all_units = list(dict.fromkeys(predecessor_units + problem_units))
        a("inductive ProblemId where")
        for unit in all_units:
            a(f"  | {camel(unit)}")
        a("  deriving DecidableEq, Repr")
        a("")
        if stage == "confirmation":
            a("def pilotUnitIds : List ProblemId := [")
            for unit in predecessor_units:
                a(f"  .{camel(unit)},")
            a("]")
            a("")
        a(f"def {'confirmation' if stage == 'confirmation' else 'pilot'}UnitIds : List ProblemId := [")
        for unit in problem_units:
            a(f"  .{camel(unit)},")
        a("]")
        a("")
        if stage == "confirmation":
            a("theorem unitIds_disjoint : pilotUnitIds.Disjoint confirmationUnitIds := by")
            a("  native_decide")
            a("")

    variation_expr = f"VariationPlan.{endpoint_kind} {endpoint_name}"
    if stage == "pilot":
        a("def replicationPlan := ReplicationPlan.pilot")
        a("  pilotUnitIds (by native_decide)")
        a(f"  ({variation_expr})")
    else:
        a("def replicationPlan := ReplicationPlan.confirmation predecessorEndpoint")
        a("  pilotUnitIds confirmationUnitIds (by native_decide) (by native_decide)")
        a("  unitIds_disjoint")
        a(f"  ({variation_expr})")
    a("")

    claim_map = {
        "comparative": "ClaimForm.comparative",
        "descriptive": "ClaimForm.descriptive",
        "rarer-than-chance": "ClaimForm.rarerThanChance",
    }
    claim = kw(design.get("claim"))
    if claim not in claim_map:
        raise ValueError(f"unsupported claim form :{claim}")
    budget = plain_map(design["budget"])
    arms_expr = ", ".join(arm_names[kw(arm["id"])] for arm in arms)
    a("noncomputable def baseRegistration : Registration ExperimentTrace where")
    a(f"  name := {lean_string(eid)}")
    a(f"  claim := {claim_map[claim]}")
    a(f"  arms := [{arms_expr}]")
    a("  flags := []")
    a(f"  estimatedCost := {lean_num(budget['estimated-cell-runs'])}")
    a(f"  budgetCap := {lean_num(budget['cap-cell-runs'])}")
    a("  teardownDeadline := some 1")
    a("")
    a("/-- The concrete teardown commitment retained alongside the existing")
    a("`Registration.teardownDeadline` marker. -/")
    a(f"def teardownCommitment : String := {lean_string(budget['teardown'])}")
    a("")
    a("noncomputable def prospectiveRegistration :")
    unit_type = "Nat" if seedable else "ProblemId"
    a(f"    ProspectiveRegistration {unit_type} ExperimentTrace Outcome where")
    a("  base := baseRegistration")
    a("  replication := replicationPlan")
    a(f"  stopRules := [{stop_name}]")
    a("  stopRulesNonempty := by simp")
    a("  decision := decisionRule")
    a("")
    a("def readinessEvidence : Evidence where")
    a("  toolchainExercised := true")
    a("  codeIdentityAsserted := true")
    a("  teardownExercised := true")
    a("  armsShownDistinct := true")
    a("")
    a("def readinessSmoke : ExperimentTrace where")
    a(f"  classification := TraceClass.{trace_classes[0]}")
    a("  positiveControlViolated := false")
    a("")
    obligation_proofs = []
    for arm in arms:
        is_positive = kw(arm.get("role")) == "positive-control"
        for axis_id_value in arm.get("ablates", []):
            axis_name = axis_names[kw(axis_id_value)]
            suffix = "predicted_not_navigable" if is_positive else "navigable"
            obligation_proofs.append(f"exact {axis_name}_{suffix}")
    if claim == "comparative":
        obligation_proofs.append("rfl")
    elif claim == "rarer-than-chance":
        neutral_arms = [arm_names[kw(arm["id"])] for arm in arms
                        if bool(arm.get("neutral?"))]
        if not neutral_arms:
            raise ValueError("rarer-than-chance registration requires a neutral control arm")
        neutral_arm = neutral_arms[0]
        obligation_proofs.append(
            f"exact ⟨{neutral_arm}, by simp [baseRegistration], by simp [{neutral_arm}]⟩"
        )
    a("noncomputable def baseReadyToRun :")
    a("    ReadyToRun baseRegistration readinessEvidence readinessSmoke where")
    a("  apparatus := by simp [Evidence.apparatusSound, readinessEvidence]")
    a("  discharged := by")
    a("    intro o ho")
    arm_defs = ", ".join(arm_names[kw(arm["id"])] for arm in arms)
    a(f"    simp [Registration.obligations, baseRegistration, {arm_defs}] at ho")
    if obligation_proofs:
        cases = " | ".join(["rfl"] * len(obligation_proofs) + ["h"])
        a(f"    rcases ho with ({cases})")
        for proof in obligation_proofs:
            a(f"    · {proof}")
        a("    · rcases h with (rfl | rfl)")
    else:
        a("    rcases ho with (rfl | rfl)")
    a("      · norm_num [Discharged, baseRegistration]")
    a("      · rfl")
    a("")
    a("noncomputable def prospectiveReadyToRun :")
    a("    ProspectiveReadyToRun prospectiveRegistration readinessEvidence readinessSmoke where")
    a("  baseReady := by simpa [prospectiveRegistration] using baseReadyToRun")
    a("  smokeClear := by")
    a("    intro s hs")
    a("    simp only [prospectiveRegistration, List.mem_singleton] at hs")
    a("    subst s")
    a("    rfl")
    a("")
    a("example : prospectiveRegistration.stopRules ≠ [] := by decide")
    a(f"example : prospectiveRegistration.replication.stage = RegistrationStage.{stage} := rfl")
    if stage == "confirmation":
        a("example : pilotUnitIds.Disjoint confirmationUnitIds := unitIds_disjoint")
    for axis in axes:
        if not bool(axis.get("score-varies?")):
            axis_name = axis_names[kw(axis["id"])]
            a(f"example : ¬ {axis_name}.Navigable := {axis_name}_predicted_not_navigable")
    positive_arms = [arm for arm in arms if kw(arm.get("role")) == "positive-control"]
    if positive_arms:
        positive_arm = positive_arms[0]
        positive_axis_id = kw(list(positive_arm["ablates"])[0])
        positive_axis = axis_names[positive_axis_id]
        positive_arm_name = arm_names[kw(positive_arm["id"])]
        a("")
        a("/-- The positive control's dead axis is an explicit prediction, not")
        a("an accidentally accepted treatment axis. -/")
        a("theorem positiveControl_nonNavigability_registered :")
        a(f"    Obligation.axisPredictedNonNavigable {positive_axis} ∈")
        a("      baseRegistration.obligations ∧")
        a(f"      ¬ {positive_axis}.Navigable := by")
        a("  constructor")
        a(f"  · exact mem_obligations_axisPredictedNonNavigable")
        a(f"      (a := {positive_arm_name}) (by simp [baseRegistration])")
        a(f"      (by simp [{positive_arm_name}]) (by simp [{positive_arm_name}])")
        a(f"  · exact {positive_axis}_predicted_not_navigable")
    a("")
    a(f"end {ns}")
    return "\n".join(L)


def emit_proof(d, include_sorry_discharge_check=True):
    pid = kw(d["proof"])
    boxes = boxes_of(d)
    wires = wires_of(d)
    seq = [kw(x) for x in d["seq"]]
    # sanitize step ids to valid Lean identifiers (hand ids s1.. are unchanged;
    # producer ids like e-direct -> eDirect). Claim ids in consumes/produces are
    # not emitted to Lean, so they need no remap.
    idmap = {b["id"]: camel(b["id"]) for b in boxes}
    for b in boxes:
        b["id"] = idmap[b["id"]]
    for w in wires:
        w["from"] = idmap.get(w["from"], camel(w["from"]))
        w["to"] = idmap.get(w["to"], camel(w["to"]))
    # Domain copar extensions (E-scope-organism-copar). A CLean may declare its
    # own :readings (e.g. scope∥organism) and :co-app meets (the cascade
    # semilattice's BV.copar overlaps). Both live in :clean/shape. When absent,
    # every line below is byte-identical to the informal∥formal default — the
    # 102-paper / fold corpus renders unchanged.
    _shape = {kw(k): v for k, v in dict(d.get("shape") or {}).items()}
    domain_readings = [camel(kw(x)) for x in (_shape.get("readings") or [])]
    coapp_pairs = [(idmap.get(kw(e[0]), camel(kw(e[0]))),
                    idmap.get(kw(e[1]), camel(kw(e[1]))))
                   for e in (_shape.get("co-app") or []) if len(e) >= 2]
    # mission ids carry hyphens (autoclock-in, <repo>-d/mission/<id>); a Lean
    # namespace identifier cannot. Sanitize hyphens->underscores for the ns
    # (the comment on the next line keeps the original id for provenance).
    ns = f"CLeanProof_{pid.replace('-', '_')}"
    L = []
    a = L.append

    a(f"namespace {ns}")
    a(f"-- {pid}: {d.get('title','')}")
    a("")

    # Method inductive (distinct tags, in first-seen order)
    methods, seen = [], set()
    for m in seq:
        if m not in seen:
            seen.add(m); methods.append(m)
    a("/-- The iching/CT method tags appearing in this proof's spine. -/")
    a("inductive Method where")
    for m in methods:
        a(f"  | {camel(m)}")
    a("  deriving DecidableEq, Repr")
    a("")

    # spine as nested BV.seq
    a("/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/")
    atoms = [f"BV.atom Method.{camel(m)}" for m in seq]
    def nest(xs):
        if len(xs) == 1:
            return xs[0]
        return f"BV.seq ({xs[0]}) ({nest(xs[1:])})"
    a("def spine : BV Method :=")
    a("  " + nest(atoms))
    a("")

    # Steps
    a("/-- The proof steps (the comb positions). -/")
    a("inductive Stp where")
    for b in boxes:
        a(f"  | {b['id']}")
    a("  deriving DecidableEq, Repr")
    a("")

    # Obligation
    a("/-- The direction a still-open typed hole exposes: an outstanding proof. -/")
    a("inductive Obligation where")
    a("  | proof")
    a("  deriving DecidableEq, Repr")
    a("")

    # holes : TypedHole
    a("/-- The typed-hole interface: each step is a position; a step exposes an")
    a("    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/")
    a("def holes : TypedHole where")
    a("  poly :=")
    a("    { A := Stp")
    a("      B := fun")
    for b in boxes:
        d_ty = "Obligation" if "hole" in b else "Empty"
        a(f"        | Stp.{b['id']} => {d_ty}")
    a("    }")
    a("  satiety := fun")
    for b in boxes:
        grade = b["hole"]["satiety"] if "hole" in b else "canon"  # discharged -> canon default
        a(f"    | Stp.{b['id']} => SatietyGrade.{grade}")
    a("")

    # discharges to known
    disch = [(b["id"], b["discharges"]["to"]) for b in boxes if "discharges" in b]
    if disch:
        known, kseen = [], set()
        for _, t in disch:
            if t not in kseen:
                kseen.add(t); known.append(t)
        a("/-- Named results the reduce-to-known steps discharge to. -/")
        a("inductive KnownResult where")
        for t in known:
            a(f"  | {camel(t)}")
        a("  deriving DecidableEq, Repr")
        a("")
        a("/-- Which steps discharge to a named theorem (carry no open hole). -/")
        a("def discharges : Stp -> Option KnownResult")
        for sid, t in disch:
            a(f"  | Stp.{sid} => some KnownResult.{camel(t)}")
        a("  | _ => none")
        a("")

    # wires (comb edges, as data)
    a("/-- The comb wiring (construct -> consume edges). -/")
    wlist = ", ".join(f"(Stp.{w['from']}, Stp.{w['to']})" for w in wires)
    a(f"def wires : List (Stp × Stp) := [{wlist}]")
    a("")

    # co-application MEETS — the semilattice's BV.copar overlaps, as data. A
    # single position may sit in several meets at once: this is what makes the
    # cascade a semilattice, not a tree (TN-a-proof-is-not-a-tree).
    if coapp_pairs:
        mlist = ", ".join(f"(Stp.{a2}, Stp.{b2})" for (a2, b2) in coapp_pairs)
        a("/-- The co-application meets (BV.copar overlaps): the semilattice's cross-cuts. -/")
        a(f"def meets : List (Stp × Stp) := [{mlist}]")
        a("")

    # copar reading — the CLean's declared domain readings, else informal ∥ formal.
    if len(domain_readings) >= 2:
        rlist = domain_readings
        def _rcopar(xs):
            return (f"BV.atom Reading.{xs[0]}" if len(xs) == 1
                    else f"BV.copar (BV.atom Reading.{xs[0]}) ({_rcopar(xs[1:])})")
        a(f"/-- The readings held together (M-typed-holes copar): {' ∥ '.join(rlist)}. -/")
        a("inductive Reading where")
        for rn in rlist:
            a(f"  | {rn}")
        a("  deriving DecidableEq, Repr")
        a("def readings : BV Reading :=")
        a(f"  {_rcopar(rlist)}")
    else:
        rlist = ["informal", "formal"]
        a("/-- The two readings held together (M-typed-holes copar): informal ∥ formal. -/")
        a("inductive Reading where")
        a("  | informal | formal")
        a("  deriving DecidableEq, Repr")
        a("def readings : BV Reading :=")
        a("  BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)")
    a("")

    # --- self-verifying examples (0 sorry) ---
    if include_sorry_discharge_check:
        a("-- Self-verifying checks: the render is type-correct and computes. 0 sorry.")
    else:
        a("-- Self-verifying checks: the experiment pipeline is type-correct and computes.")
    for b in boxes:
        if "hole" in b:
            a(f"example : holes.holeType Stp.{b['id']} = Obligation := rfl")
        else:
            a(f"example : holes.holeType Stp.{b['id']} = Empty := rfl")
    for b in boxes:
        grade = b["hole"]["satiety"] if "hole" in b else "canon"
        a(f"example : holes.satiety Stp.{b['id']} = SatietyGrade.{grade} := rfl")
    if disch:
        for sid, t in disch:
            a(f"example : discharges Stp.{sid} = some KnownResult.{camel(t)} := rfl")
    if include_sorry_discharge_check:
        a("/-- Every open hole is a sorry/proof hole. -/")
        a("example : DischargeKind.sorryProof = DischargeKind.sorryProof := rfl")
    if len(seq) >= 3:
        m0, m1, m2 = camel(seq[0]), camel(seq[1]), camel(seq[2])
        a("/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/")
        a("example : BV.Cong")
        a(f"    (BV.seq (BV.seq (BV.atom Method.{m0}) (BV.atom Method.{m1})) (BV.atom Method.{m2}))")
        a(f"    (BV.seq (BV.atom Method.{m0}) (BV.seq (BV.atom Method.{m1}) (BV.atom Method.{m2}))) :=")
        a(f"  BV.Cong.seq_assoc (BV.atom Method.{m0}) (BV.atom Method.{m1}) (BV.atom Method.{m2})")
    if len(domain_readings) >= 2:
        r0, r1 = rlist[0], rlist[1]
        a(f"/-- The {r0} ∥ {r1} copar reading commutes (one object, its readings). -/")
        a(f"example : BV.Cong (BV.copar (BV.atom Reading.{r0}) (BV.atom Reading.{r1})) (BV.copar (BV.atom Reading.{r1}) (BV.atom Reading.{r0})) :=")
        a(f"  BV.Cong.copar_comm (BV.atom Reading.{r0}) (BV.atom Reading.{r1})")
    else:
        a("/-- The informal ∥ formal copar reading commutes (one object, two readings). -/")
        a("example : BV.Cong readings (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=")
        a("  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)")
    if coapp_pairs:
        ma, mb = coapp_pairs[0]
        a("/-- A representative co-application meet is a well-formed BV.copar and commutes:")
        a("    overlap is symmetric (a semilattice meet, not a directed wire). -/")
        a(f"example : BV.Cong (BV.copar (BV.atom Stp.{ma}) (BV.atom Stp.{mb})) (BV.copar (BV.atom Stp.{mb}) (BV.atom Stp.{ma})) :=")
        a(f"  BV.Cong.copar_comm (BV.atom Stp.{ma}) (BV.atom Stp.{mb})")
    a("")
    a(f"end {ns}")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--clean-dir", default="holes/clean")
    ap.add_argument("--mode", choices=["real", "standalone"], default="real")
    ap.add_argument("--kind", choices=["proof", "experiment"], default="proof",
                    help="render proof-shaped or experiment-shaped CLean")
    ap.add_argument("--out", required=True)
    ap.add_argument("--only", default=None, help="emit only this proof id")
    args = ap.parse_args()

    files = sorted(glob.glob(os.path.join(args.clean_dir, "*.clean.edn")))
    bodies = []
    for f in files:
        d = load_clean(f)
        identity_key = "proof" if args.kind == "proof" else "experiment"
        if identity_key not in d:
            continue
        if args.only and kw(d[identity_key]) != args.only:
            continue
        if args.kind == "proof":
            bodies.append(emit_proof(d))
        else:
            if args.mode == "standalone":
                raise SystemExit("experiment renders require --mode real (DarkTower structures)")
            # The experiment pipeline is still a CLean comb. Give it the third
            # executable reading while retaining the ordinary proof emitter.
            pipeline = dict(d)
            pipeline["proof"] = d["experiment"]
            shape = plain_map(d.get("shape") or {})
            shape["readings"] = ["informal", "formal", "executable"]
            pipeline["shape"] = shape
            try:
                bodies.append(emit_proof(pipeline, include_sorry_discharge_check=False)
                              + "\n\n" + emit_experiment(d))
            except ValueError as error:
                raise SystemExit(f"refused {f}: {error}") from None

    if args.mode == "standalone":
        # bodies reference DarkTower.* ; open the shim namespace for them
        out = SHIM + "\nopen DarkTower\n\n" + "\n\n".join(bodies) + "\n"
    else:
        header = REAL_HEADER if args.kind == "proof" else EXPERIMENT_HEADER
        out = header + "\nnamespace DarkTower\nopen CategoryTheory\n\n" \
            + "\n\n".join(bodies) + "\n\nend DarkTower\n"

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write(out)
    print(f"wrote {args.out}  ({len(bodies)} {args.kind}s, mode={args.mode})")


if __name__ == "__main__":
    main()
