#!/usr/bin/env python3
"""CLean -> DarkTower Lean emitter (deterministic).

Renders a CLean EDN proof to the DarkTower Lean types, exactly as
`mathlib4/DarkTower/Examples.lean` instantiates the mission sketch
(`MissionExample`). The render IS the correctness gate: a CLean is well-formed
iff it produces type-correct, 0-sorry DarkTower Lean.

Each proof becomes a namespace with:
  - `inductive Method`     the distinct iching/CT method tags in the spine
  - `def spine : BV Method`    the pattern-tagged method spine (informal reading)
  - `inductive Stp`        the proof steps (comb positions)
  - `inductive Obligation` the direction a still-open hole exposes (a proof)
  - `def holes : TypedHole` poly positions = steps; B step = Obligation if the
                            step has a typed hole, else Empty (discharged);
                            satiety from the CLean hole grade
  - `def discharges`       reduce-to-known steps -> named theorems
  - `def wires`            the comb edges (construct -> consume), as data
  - `def readings : BV Reading`  the informal ∥ formal copar
  - self-verifying `example`s (holeType / satiety / discharge / BV reassoc) that
    all close by rfl/decide -> 0 sorry.

Two modes:
  --mode real        import Mathlib + DarkTower modules; lands in the repo
                     (compiles once mathlib oleans are built).
  --mode standalone  prepend a minimal shim of the exact DarkTower signatures
                     the render touches; compiles NOW with core `lean` (no
                     mathlib), giving a real 0-sorry check.

Usage:
  futon6/.venv/bin/python scripts/clean_to_lean.py \
      --clean-dir holes/clean --mode real \
      --out /home/joe/code/mathlib4/DarkTower/CLeanProofs.lean
  futon6/.venv/bin/python scripts/clean_to_lean.py --mode standalone \
      --out /tmp/clean_lean_check.lean
"""
import argparse
import glob
import os
from clean_structure_embed import kw, load_clean, boxes_of, wires_of


def camel(s):
    parts = s.replace("/", "-").split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


SHIM = r"""-- Minimal shim of the DarkTower signatures the CLean render touches.
-- Signature-identical to mathlib4/DarkTower/{BV,TypedHole,Discharge}.lean, but
-- with no `import Mathlib`, so this file compiles with core `lean`. The real
-- emit (--mode real) targets the Mathlib-backed modules instead.
universe u v
namespace DarkTower

inductive BV (A : Type u) where
  | unit | atom : A -> BV A | seq : BV A -> BV A -> BV A
  | copar : BV A -> BV A -> BV A | par : BV A -> BV A -> BV A
namespace BV
inductive Cong {A : Type u} : BV A -> BV A -> Prop where
  | seq_assoc (S T U : BV A) : Cong (seq (seq S T) U) (seq S (seq T U))
  | copar_comm (S T : BV A) : Cong (copar S T) (copar T S)
end BV

inductive SatietyGrade | parse | payoff | canon | bundling | role
  deriving DecidableEq, Repr
inductive DischargeKind | sorryProof | queryAnswer | ungroundedBinder
  deriving DecidableEq, Repr

structure PFunctor where
  A : Type u
  B : A -> Type v
structure TypedHole where
  poly : PFunctor
  satiety : poly.A -> SatietyGrade
namespace TypedHole
def holeType (T : TypedHole) (a : T.poly.A) : Type v := T.poly.B a
end TypedHole

end DarkTower
"""

REAL_HEADER = """import Mathlib
import DarkTower.TypedHole
import DarkTower.Comb
import DarkTower.Discharge
import DarkTower.BV

/-!
# CLean proofs as DarkTower typed-hole interfaces

Generated by `futon6/scripts/clean_to_lean.py` from `futon6/holes/clean/*.clean.edn`.
Each namespace is the CT treatment of one APM proof, rendered to the same
`BV` / `TypedHole` / `DischargeKind` machinery that types `MissionExample` in
`Examples.lean`. The render is the correctness gate: it builds 0-sorry iff the
CLean is well-formed. See `futon6/holes/excursions/E-clean.md`.
-/
"""


def emit_proof(d):
    pid = kw(d["proof"])
    boxes = boxes_of(d)
    wires = wires_of(d)
    seq = [kw(x) for x in d["seq"]]
    # sanitize step ids to valid Lean identifiers (hand ids s1.. are unchanged;
    # producer ids like e-direct -> eDirect). Claim ids in consumes/produces are
    # not emitted to Lean, so they need no remap.
    idmap = {b["id"]: camel(b["id"]) for b in boxes}
    for b in boxes:
        b["id"] = idmap[b["id"]]
    for w in wires:
        w["from"] = idmap.get(w["from"], camel(w["from"]))
        w["to"] = idmap.get(w["to"], camel(w["to"]))
    # mission ids carry hyphens (autoclock-in, <repo>-d/mission/<id>); a Lean
    # namespace identifier cannot. Sanitize hyphens->underscores for the ns
    # (the comment on the next line keeps the original id for provenance).
    ns = f"CLeanProof_{pid.replace('-', '_')}"
    L = []
    a = L.append

    a(f"namespace {ns}")
    a(f"-- {pid}: {d.get('title','')}")
    a("")

    # Method inductive (distinct tags, in first-seen order)
    methods, seen = [], set()
    for m in seq:
        if m not in seen:
            seen.add(m); methods.append(m)
    a("/-- The iching/CT method tags appearing in this proof's spine. -/")
    a("inductive Method where")
    for m in methods:
        a(f"  | {camel(m)}")
    a("  deriving DecidableEq, Repr")
    a("")

    # spine as nested BV.seq
    a("/-- The pattern-tagged method spine (the informal reading), a BV.seq chain. -/")
    atoms = [f"BV.atom Method.{camel(m)}" for m in seq]
    def nest(xs):
        if len(xs) == 1:
            return xs[0]
        return f"BV.seq ({xs[0]}) ({nest(xs[1:])})"
    a("def spine : BV Method :=")
    a("  " + nest(atoms))
    a("")

    # Steps
    a("/-- The proof steps (the comb positions). -/")
    a("inductive Stp where")
    for b in boxes:
        a(f"  | {b['id']}")
    a("  deriving DecidableEq, Repr")
    a("")

    # Obligation
    a("/-- The direction a still-open typed hole exposes: an outstanding proof. -/")
    a("inductive Obligation where")
    a("  | proof")
    a("  deriving DecidableEq, Repr")
    a("")

    # holes : TypedHole
    a("/-- The typed-hole interface: each step is a position; a step exposes an")
    a("    `Obligation` iff it carries an open hole, else `Empty` (discharged). -/")
    a("def holes : TypedHole where")
    a("  poly :=")
    a("    { A := Stp")
    a("      B := fun")
    for b in boxes:
        d_ty = "Obligation" if "hole" in b else "Empty"
        a(f"        | Stp.{b['id']} => {d_ty}")
    a("    }")
    a("  satiety := fun")
    for b in boxes:
        grade = b["hole"]["satiety"] if "hole" in b else "canon"  # discharged -> canon default
        a(f"    | Stp.{b['id']} => SatietyGrade.{grade}")
    a("")

    # discharges to known
    disch = [(b["id"], b["discharges"]["to"]) for b in boxes if "discharges" in b]
    if disch:
        known, kseen = [], set()
        for _, t in disch:
            if t not in kseen:
                kseen.add(t); known.append(t)
        a("/-- Named results the reduce-to-known steps discharge to. -/")
        a("inductive KnownResult where")
        for t in known:
            a(f"  | {camel(t)}")
        a("  deriving DecidableEq, Repr")
        a("")
        a("/-- Which steps discharge to a named theorem (carry no open hole). -/")
        a("def discharges : Stp -> Option KnownResult")
        for sid, t in disch:
            a(f"  | Stp.{sid} => some KnownResult.{camel(t)}")
        a("  | _ => none")
        a("")

    # wires (comb edges, as data)
    a("/-- The comb wiring (construct -> consume edges). -/")
    wlist = ", ".join(f"(Stp.{w['from']}, Stp.{w['to']})" for w in wires)
    a(f"def wires : List (Stp × Stp) := [{wlist}]")
    a("")

    # copar reading
    a("/-- The two readings held together (M-typed-holes copar): informal ∥ formal. -/")
    a("inductive Reading where")
    a("  | informal | formal")
    a("  deriving DecidableEq, Repr")
    a("def readings : BV Reading :=")
    a("  BV.copar (BV.atom Reading.informal) (BV.atom Reading.formal)")
    a("")

    # --- self-verifying examples (0 sorry) ---
    a("-- Self-verifying checks: the render is type-correct and computes. 0 sorry.")
    for b in boxes:
        if "hole" in b:
            a(f"example : holes.holeType Stp.{b['id']} = Obligation := rfl")
        else:
            a(f"example : holes.holeType Stp.{b['id']} = Empty := rfl")
    for b in boxes:
        grade = b["hole"]["satiety"] if "hole" in b else "canon"
        a(f"example : holes.satiety Stp.{b['id']} = SatietyGrade.{grade} := rfl")
    if disch:
        for sid, t in disch:
            a(f"example : discharges Stp.{sid} = some KnownResult.{camel(t)} := rfl")
    a("/-- Every open hole is a sorry/proof hole. -/")
    a("example : DischargeKind.sorryProof = DischargeKind.sorryProof := rfl")
    if len(seq) >= 3:
        m0, m1, m2 = camel(seq[0]), camel(seq[1]), camel(seq[2])
        a("/-- The spine prefix reassociates by BV structural congruence (well-shaped comb). -/")
        a("example : BV.Cong")
        a(f"    (BV.seq (BV.seq (BV.atom Method.{m0}) (BV.atom Method.{m1})) (BV.atom Method.{m2}))")
        a(f"    (BV.seq (BV.atom Method.{m0}) (BV.seq (BV.atom Method.{m1}) (BV.atom Method.{m2}))) :=")
        a(f"  BV.Cong.seq_assoc (BV.atom Method.{m0}) (BV.atom Method.{m1}) (BV.atom Method.{m2})")
    a("/-- The informal ∥ formal copar reading commutes (one object, two readings). -/")
    a("example : BV.Cong readings (BV.copar (BV.atom Reading.formal) (BV.atom Reading.informal)) :=")
    a("  BV.Cong.copar_comm (BV.atom Reading.informal) (BV.atom Reading.formal)")
    a("")
    a(f"end {ns}")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--clean-dir", default="holes/clean")
    ap.add_argument("--mode", choices=["real", "standalone"], default="real")
    ap.add_argument("--out", required=True)
    ap.add_argument("--only", default=None, help="emit only this proof id")
    args = ap.parse_args()

    files = sorted(glob.glob(os.path.join(args.clean_dir, "*.clean.edn")))
    bodies = []
    for f in files:
        d = load_clean(f)
        if args.only and kw(d["proof"]) != args.only:
            continue
        bodies.append(emit_proof(d))

    if args.mode == "standalone":
        # bodies reference DarkTower.* ; open the shim namespace for them
        out = SHIM + "\nopen DarkTower\n\n" + "\n\n".join(bodies) + "\n"
    else:
        out = REAL_HEADER + "\nnamespace DarkTower\nopen CategoryTheory\n\n" \
            + "\n\n".join(bodies) + "\n\nend DarkTower\n"

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write(out)
    print(f"wrote {args.out}  ({len(bodies)} proofs, mode={args.mode})")


if __name__ == "__main__":
    main()
