#!/usr/bin/env python3
"""Generate a wiring diagram for Problem 5 (O-slice connectivity via geometric fixed points)."""
import argparse, json, os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from futon6.thread_performatives import (
    ThreadNode, ThreadEdge, ThreadWiringDiagram, diagram_to_dict, diagram_stats,
)

def build_proof_diagram() -> ThreadWiringDiagram:
    diagram = ThreadWiringDiagram(thread_id="first-proof-p5")
    diagram.nodes = [
        ThreadNode(id="p5-problem", node_type="question", post_id=5,
            body_text="Define O-slice filtration for incomplete transfer system O and characterize O-slice connectivity of connective G-spectrum via geometric fixed points.",
            score=0, creation_date="2026-02-11"),
        ThreadNode(id="p5-s1", node_type="answer", post_id=501,
            body_text="Classical regular slice filtration is generated by cells G_+ wedge_H S^{k rho_H} (Hill-Yarnall Def. 1.1). Geometric fixed points detect these cells (Thm. 2.5).",
            score=0, creation_date="2026-02-11", parent_post_id=5),
        ThreadNode(id="p5-s2", node_type="answer", post_id=502,
            body_text="N_infinity operad O gives transfer/indexing data (Blumberg-Hill Def. 1.1, Thm. 1.2); it restricts admissible subgroup transfers, not a new O-regular representation.",
            score=0, creation_date="2026-02-11", parent_post_id=5),
        ThreadNode(id="p5-s3", node_type="answer", post_id=503,
            body_text="Define tau_{>=n}^O by restricting regular slice generators to allowed subgroups H in F_O: cells G_+ wedge_H S^{k rho_H} with k|H| >= n.",
            score=0, creation_date="2026-02-11", parent_post_id=5),
        ThreadNode(id="p5-s4", node_type="answer", post_id=504,
            body_text="Characterization: for connective X, X in tau_{>=n}^O iff Phi^H X is (ceil(n/|H|)-1)-connected for all H in F_O, mirroring Hill-Yarnall Thm. A / Thm. 2.5 on the restricted subgroup family.",
            score=0, creation_date="2026-02-11", parent_post_id=5),
        ThreadNode(id="p5-s5", node_type="answer", post_id=505,
            body_text="Proof sketch: Phi^H(G_+ wedge_H S^{k rho_H}) ~= S^k, so vanishing maps from generators with k|H|<n is equivalent to vanishing pi_i(Phi^H X) for i<ceil(n/|H|).",
            score=0, creation_date="2026-02-11", parent_post_id=5),
        ThreadNode(id="p5-s6", node_type="answer", post_id=506,
            body_text="Special cases: complete transfer system recovers regular slice test; trivial system gives Postnikov; intermediate systems check only selected subgroup fixed points.",
            score=0, creation_date="2026-02-11", parent_post_id=5),
    ]
    diagram.edges = [
        ThreadEdge(source="p5-s1", target="p5-problem", edge_type="clarify",
            evidence="Regular slice generators and geometric fixed-point criterion (Hill-Yarnall Def. 1.1, Thm. 2.5)", detection="structural"),
        ThreadEdge(source="p5-s2", target="p5-problem", edge_type="clarify",
            evidence="N_infinity operads embed into indexing-system data (Blumberg-Hill Thm. 1.2)", detection="structural"),
        ThreadEdge(source="p5-s3", target="p5-s2", edge_type="reform",
            evidence="Adapt by subgroup restriction on regular slice generators", detection="structural"),
        ThreadEdge(source="p5-s3", target="p5-s1", edge_type="reform",
            evidence="Modify classical slice cells to account for incomplete transfers", detection="structural"),
        ThreadEdge(source="p5-s4", target="p5-problem", edge_type="assert",
            evidence="Main criterion: connectivity via Phi^H only for H in F_O", detection="structural"),
        ThreadEdge(source="p5-s4", target="p5-s3", edge_type="reference",
            evidence="Uses restricted regular slice cells as generators", detection="structural"),
        ThreadEdge(source="p5-s5", target="p5-s4", edge_type="assert",
            evidence="Proof via geometric fixed point detection on regular slice cells", detection="structural"),
        ThreadEdge(source="p5-s5", target="p5-s1", edge_type="reference",
            evidence="Parallels classical HHR proof structure", detection="structural"),
        ThreadEdge(source="p5-s6", target="p5-s4", edge_type="exemplify",
            evidence="Complete/trivial/intermediate systems reduce as expected", detection="structural"),
        ThreadEdge(source="p5-s6", target="p5-s1", edge_type="reference",
            evidence="Complete case recovers the usual regular-slice fixed-point criterion", detection="structural"),
    ]
    return diagram

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", default="data/first-proof/problem5-wiring.json")
    parser.add_argument("--quiet", "-q", action="store_true")
    args = parser.parse_args()
    diagram = build_proof_diagram()
    if not args.quiet:
        stats = diagram_stats(diagram)
        print(f"=== Proof Wiring Diagram: {diagram.thread_id} ===")
        print(f"{stats['n_nodes']} nodes, {stats['n_edges']} edges")
        print(f"Edge types: {stats['edge_types']}")
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w") as f:
        json.dump(diagram_to_dict(diagram), f, indent=2, ensure_ascii=False)
    print(f"\nWrote {args.output}")

if __name__ == "__main__":
    main()
