#!/usr/bin/env python3
"""Polish the Problem 2 proof via Codex CLI.

For each proof node in the wiring diagram, generates a verification prompt
and runs it through `codex exec`. Codex cross-references with math.SE data
(when available), verifies mathematical claims, and identifies gaps.

Usage:
    # Generate prompts only (dry run)
    python3 scripts/run-proof-polish-codex-p2.py --dry-run

    # Run through Codex (needs math.SE data in se-data/math-processed/)
    python3 scripts/run-proof-polish-codex-p2.py --limit 9

    # With custom math.SE search path
    python3 scripts/run-proof-polish-codex-p2.py --math-se-dir se-data/math-processed/
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from collections import Counter
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
WIRING_JSON = REPO_ROOT / "data" / "first-proof" / "problem2-wiring.json"
SOLUTION_MD = REPO_ROOT / "data" / "first-proof" / "problem2-solution.md"
DEFAULT_OUTPUT = REPO_ROOT / "data" / "first-proof" / "problem2-codex-results.jsonl"
DEFAULT_PROMPTS = REPO_ROOT / "data" / "first-proof" / "problem2-codex-prompts.jsonl"
DEFAULT_MATH_SE_DIR = REPO_ROOT / "se-data" / "math-processed"


RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "node_id": {"type": "string"},
        "claim_verified": {
            "type": "string",
            "enum": ["verified", "plausible", "gap", "error"],
        },
        "verification_notes": {"type": "string"},
        "math_se_references": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "question_id": {"type": "integer"},
                    "title": {"type": "string"},
                    "relevance": {"type": "string"},
                    "site": {
                        "type": "string",
                        "enum": ["math.stackexchange.com", "mathoverflow.net", "other", "unknown"],
                    },
                },
                "required": ["question_id", "title", "relevance", "site"],
                "additionalProperties": False,
            },
        },
        "suggested_improvement": {"type": "string"},
        "missing_assumptions": {
            "type": "array",
            "items": {"type": "string"},
        },
        "confidence": {
            "type": "string",
            "enum": ["high", "medium", "low"],
        },
    },
    "required": [
        "node_id",
        "claim_verified",
        "verification_notes",
        "math_se_references",
        "suggested_improvement",
        "missing_assumptions",
        "confidence",
    ],
    "additionalProperties": False,
}


# Verification focus for each proof step
NODE_VERIFICATION_FOCUS = {
    "p2-problem": (
        "Verify the problem is well-posed: must there exist W in W(Pi, psi^{-1}) "
        "such that for all generic pi of GL_n, the u_Q-twisted Rankin-Selberg "
        "integral is finite and nonzero for all s? Check that Pi is generic "
        "irreducible admissible on GL_{n+1}(F) with F non-archimedean, psi has "
        "conductor o, and u_Q = I_{n+1} + Q E_{n,n+1} with Q generating the "
        "inverse conductor ideal of pi. Confirm 'universal test vector' is the "
        "right terminology (cf. Matringe, Miyauchi, File-Raghuram)."
    ),
    "p2-s1": (
        "Verify JPSS fractional ideal structure: do integrals over (W, V) "
        "generate L(s, Pi x pi) * C[q^s, q^{-s}]? Check this is Theorem 2.7 "
        "of Jacquet-Piatetski-Shapiro-Shalika (1983). Confirm convergence for "
        "Re(s) >> 0 and meromorphic continuation to rational function of q_F^{-s}. "
        "Is the fractional ideal generated by ALL pairs (W, V) or by varying V "
        "for fixed W? This distinction matters for the universality argument."
    ),
    "p2-s2": (
        "Check the algebraic argument: a rational function of X = q_F^{-s} that "
        "is finite and nonzero for all X in C^x must be a monomial c * X^k. "
        "Verify: a unit in C[X, X^{-1}] is indeed a monomial. Does this require "
        "f to be a Laurent polynomial, or just rational? If rational, the argument "
        "needs that f has no poles/zeros on C^x, which for f = P(X)/Q(X) with "
        "P, Q polynomials means P and Q are both monomials."
    ),
    "p2-s3": (
        "Verify R(u_Q)W is nonzero: does right translation by a unipotent element "
        "preserve the Whittaker model? Check: u_Q is upper-triangular unipotent "
        "in GL_{n+1}, so R(u_Q) maps W(Pi, psi^{-1}) to itself. But why is "
        "R(u_Q)W nonzero for W nonzero? This needs: the right regular "
        "representation on the Whittaker model is faithful, or equivalently, "
        "no nonzero W is killed by right translation by u_Q. Verify via the "
        "Kirillov model embedding."
    ),
    "p2-s4": (
        "JPSS nondegeneracy: is this for fixed W varying V, or for varying both? "
        "The proof needs: for FIXED nonzero phi_Q in the Kirillov model, the "
        "integrals over V span the full fractional ideal. Reference JPSS 1983 "
        "Section 2.7. Check whether the nondegeneracy statement in JPSS is "
        "symmetric (varying both W and V) or asymmetric (fixing one). If "
        "symmetric, an additional argument is needed to get the fixed-W version."
    ),
    "p2-s5": (
        "New vector existence and normalization: is W_0(I_{n+1}) = 1 standard? "
        "Check: the new vector (essential Whittaker function) is the unique "
        "(up to scalar) vector fixed by K_1(p^{c(Pi)}). The normalization "
        "W_0(I_{n+1}) = 1 is a convention — verify it is achievable (i.e., "
        "the new vector does not vanish at the identity). Reference: "
        "Jacquet-Piatetski-Shapiro-Shalika, or JPSS Theorem 5.1, or "
        "Reeder (1991), or Matringe (2013)."
    ),
    "p2-s6": (
        "Conductor matching mechanism: verify the Iwasawa decomposition argument. "
        "The claim is that u_Q modifies the diagonal part at scale Q = pi_F^{-c(pi)}, "
        "ensuring support overlap between the twisted Whittaker function and the "
        "new vector of pi. Check: in the Iwasawa decomposition g = nak, how does "
        "conjugation by diag(g,1) interact with u_Q? Is the 'support overlap' "
        "claim precise or heuristic? Does the argument actually use Iwasawa, or "
        "is this intuition for why u_Q is needed?"
    ),
    "p2-s7": (
        "Special cases: verify unramified x unramified gives the spherical "
        "integral. When c(Pi) = c(pi) = 0, u_Q = I + E_{n,n+1} (since Q = 1). "
        "W_0 is the spherical (K-fixed) vector. Check: does the standard "
        "unramified computation (Shintani, Casselman-Shalika) apply here? "
        "The integral with V_0 spherical should give L(s, Pi x pi) times an "
        "explicit correction. Also verify the 'Pi unramified, pi ramified' case: "
        "does the u_Q twist really implement 'conductor-lowering'?"
    ),
}


def build_node_prompt(
    node: dict,
    edges: list[dict],
    solution_text: str,
    math_se_dir: Path | None = None,
) -> str:
    """Build a verification prompt for a single proof node."""
    node_id = node["id"]
    focus = NODE_VERIFICATION_FOCUS.get(node_id, "Verify the mathematical claim.")

    # Find edges involving this node
    incoming = [e for e in edges if e["target"] == node_id]
    outgoing = [e for e in edges if e["source"] == node_id]

    lines = [
        "You are a mathematical proof verifier with expertise in "
        "automorphic forms, local Langlands, Rankin-Selberg integrals, "
        "Whittaker models, p-adic representation theory.",
        "",
        "## Task",
        "",
        "Verify one step of a proof that a universal test vector exists for "
        "the local Rankin-Selberg integral on GL_{n+1} x GL_n: the new vector "
        "(essential Whittaker function) of Pi, with a u_Q twist compensating "
        "for the conductor of pi. "
        "Cross-reference with math.SE/MO discussions and the primary sources "
        "(JPSS 1983, Matringe 2013, File-Raghuram) when possible.",
        "",
        "## Proof Step Under Review",
        "",
        f"**Node ID**: {node_id}",
        f"**Type**: {node['node_type']}",
        f"**Claim**: {node['body_text']}",
        "",
        "## Verification Focus",
        "",
        focus,
        "",
    ]

    if incoming:
        lines.append("## Incoming Edges (this step depends on)")
        for e in incoming:
            lines.append(f"  - {e['source']} -> {node_id} [{e['edge_type']}]: {e['evidence']}")
        lines.append("")

    if outgoing:
        lines.append("## Outgoing Edges (this step supports)")
        for e in outgoing:
            lines.append(f"  - {node_id} -> {e['target']} [{e['edge_type']}]: {e['evidence']}")
        lines.append("")

    lines.extend([
        "## Full Problem Context",
        "",
        "Problem 2 asks: must there exist W in W(Pi, psi^{-1}) such that for "
        "all generic irreducible admissible pi of GL_n(F), the u_Q-twisted "
        "Rankin-Selberg integral is finite and nonzero for all s in C?",
        "",
        "The answer is: Yes. The new vector (essential Whittaker function) W_0 "
        "of Pi serves as a universal test vector. For each pi with conductor "
        "ideal q, the twist u_Q = I_{n+1} + Q E_{n,n+1} (Q generating q^{-1}) "
        "ensures the Rankin-Selberg pairing is nondegenerate. Then V can be "
        "chosen from the fractional ideal to make the integral a nonzero "
        "monomial c * q_F^{-ks}, which is finite and nonzero for all s.",
        "",
        "Key references: Jacquet-Piatetski-Shapiro-Shalika (1983), "
        "Matringe (2013), File-Raghuram.",
        "",
        "## Instructions",
        "",
        "1. Verify the mathematical claim in this proof step.",
        "2. Search math.SE/MO for relevant discussions (Rankin-Selberg integrals, "
        "Whittaker models, new vectors, Kirillov model, local L-factors, "
        "conductor exponent, JPSS theory, test vectors for GL_n).",
        "3. Identify any gaps, unstated assumptions, or potential errors.",
        "4. Suggest improvements if the claim could be tightened or clarified.",
        "5. For each reference, include `site` when known "
        "(e.g., `mathoverflow.net` or `math.stackexchange.com`).",
        "6. Reply as a single JSON object matching the required schema.",
    ])
    if math_se_dir:
        lines.extend([
            "",
            "## Local Corpus Hint",
            "",
            f"Use local processed data if available under: {math_se_dir}",
        ])

    return "\n".join(lines)


def build_synthesis_prompt(
    solution_text: str,
    wiring: dict,
    math_se_dir: Path | None = None,
) -> str:
    """Build a synthesis prompt that reviews the entire proof."""
    stats = wiring.get("stats", {})
    lines = [
        "You are a mathematical proof verifier reviewing a complete proof.",
        "",
        "## Task",
        "",
        "Review this proof that the new vector (essential Whittaker function) of "
        "Pi is a universal test vector for the Rankin-Selberg integral on "
        "GL_{n+1} x GL_n, with the u_Q twist compensating for conductor. "
        "Assess completeness, correctness, and suggest improvements.",
        "",
        "## Proof",
        "",
        solution_text,
        "",
        "## Wiring Diagram Summary",
        "",
        f"Nodes: {stats.get('n_nodes', '?')}, Edges: {stats.get('n_edges', '?')}",
        f"Edge types: {json.dumps(stats.get('edge_types', {}))}",
        "",
        "## Instructions",
        "",
        "1. Is the proof complete? Does the answer follow from the stated steps?",
        "2. Are there unstated assumptions (e.g., about the residual characteristic "
        "of F, the genericity of Pi, whether psi has conductor exactly o, "
        "whether Pi is supercuspidal/discrete-series/generic-principal-series)?",
        "3. The nondegeneracy claim (Section 4) is the crux: does JPSS 1983 "
        "Section 2.7 actually give nondegeneracy for FIXED phi_Q varying V, or "
        "does it require varying both? If the latter, the proof has a gap.",
        "4. The conductor matching argument (Section 6) is heuristic: is the "
        "Iwasawa decomposition reasoning rigorous, or does it need a more "
        "careful analysis of support conditions in the Kirillov model?",
        "5. Search math.SE/MO for: universal test vector Rankin-Selberg, new "
        "vector Whittaker model, JPSS fractional ideal, Kirillov model "
        "nondegeneracy, conductor exponent GL_n, Matringe test vector.",
        "6. Suggest a tighter or more elegant statement of the main result.",
        "7. For each reference, include `site` when known "
        "(e.g., `mathoverflow.net` or `math.stackexchange.com`).",
        "8. Reply as a single JSON object matching the required schema. "
        "Use node_id='p2-synthesis' for the synthesis.",
    ]
    if math_se_dir:
        lines.extend([
            "",
            "## Local Corpus Hint",
            "",
            f"Use local processed data if available under: {math_se_dir}",
        ])
    return "\n".join(lines)


def run_codex_once(
    codex_bin: str,
    model: str,
    cwd: Path,
    schema_path: Path,
    prompt_text: str,
) -> tuple[int, str, str]:
    """Run a single prompt through codex exec."""
    with tempfile.NamedTemporaryFile("w+", suffix=".txt", delete=False) as out_f:
        out_path = Path(out_f.name)

    instruction = (
        "You must answer exactly as one JSON object matching the required schema. "
        "Do not wrap JSON in markdown fences. Do not add extra commentary.\n\n"
        + prompt_text
    )
    cmd = [
        codex_bin,
        "exec",
        "--cd", str(cwd),
        "--sandbox", "workspace-write",
        "--model", model,
        "--output-schema", str(schema_path),
        "--output-last-message", str(out_path),
        "-",
    ]
    proc = subprocess.run(cmd, input=instruction, text=True, capture_output=True)
    try:
        response_text = out_path.read_text(encoding="utf-8").strip()
    except FileNotFoundError:
        response_text = ""
    out_path.unlink(missing_ok=True)
    return proc.returncode, response_text, proc.stderr.strip()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--wiring", type=Path, default=WIRING_JSON)
    ap.add_argument("--solution", type=Path, default=SOLUTION_MD)
    ap.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    ap.add_argument("--prompts-out", type=Path, default=DEFAULT_PROMPTS)
    ap.add_argument("--limit", type=int, default=None,
                    help="Max prompts to process (default: all generated prompts)")
    ap.add_argument("--model", default="gpt-5.3-codex")
    ap.add_argument("--codex-bin", default="codex")
    ap.add_argument("--dry-run", action="store_true",
                    help="Generate prompts only, don't call Codex")
    ap.add_argument("--math-se-dir", type=Path, default=DEFAULT_MATH_SE_DIR,
                    help="Local processed StackExchange data directory (hinted to Codex prompts)")
    ap.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    args = ap.parse_args()

    # Load wiring diagram
    if not args.wiring.exists():
        print(f"Wiring diagram not found: {args.wiring}", file=sys.stderr)
        print("Run: python3 scripts/proof2-wiring-diagram.py", file=sys.stderr)
        return 2
    wiring = json.loads(args.wiring.read_text())

    # Load solution
    solution_text = ""
    if args.solution.exists():
        solution_text = args.solution.read_text()

    nodes = wiring["nodes"]
    edges = wiring["edges"]

    # Build prompts for each node
    prompts = []
    for node in nodes:
        prompt_text = build_node_prompt(
            node,
            edges,
            solution_text,
            math_se_dir=args.math_se_dir,
        )
        prompts.append({
            "node_id": node["id"],
            "node_type": node["node_type"],
            "prompt": prompt_text,
        })

    # Add synthesis prompt
    prompts.append({
        "node_id": "p2-synthesis",
        "node_type": "synthesis",
        "prompt": build_synthesis_prompt(solution_text, wiring, math_se_dir=args.math_se_dir),
    })
    run_limit = len(prompts) if args.limit is None else min(args.limit, len(prompts))

    # Write prompts
    args.prompts_out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.prompts_out, "w") as f:
        for rec in prompts:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    print(f"Wrote {len(prompts)} prompts to {args.prompts_out}")

    if args.dry_run:
        print("Dry run -- not calling Codex.")
        print(f"\nPrompt summary ({len(prompts)} prompts, run_limit={run_limit}):")
        for p in prompts:
            lines = p["prompt"].count("\n") + 1
            print(f"  {p['node_id']:20s} [{p['node_type']:10s}] ~{lines} lines")
        return 0

    # Run through Codex
    args.output.parent.mkdir(parents=True, exist_ok=True)
    verified = Counter()
    processed = 0

    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as sf:
        json.dump(RESPONSE_SCHEMA, sf, ensure_ascii=True, indent=2)
        schema_path = Path(sf.name)

    try:
        with open(args.output, "w") as fout:
            for rec in prompts[:run_limit]:
                rc, raw_response, stderr_text = run_codex_once(
                    codex_bin=args.codex_bin,
                    model=args.model,
                    cwd=args.repo_root,
                    schema_path=schema_path,
                    prompt_text=rec["prompt"],
                )

                out = {"node_id": rec["node_id"]}
                try:
                    parsed = json.loads(raw_response)
                    if isinstance(parsed, dict):
                        out.update(parsed)
                        v = parsed.get("claim_verified", "")
                        if v in ("verified", "plausible", "gap", "error"):
                            verified[v] += 1
                    else:
                        out["parse_error"] = True
                        out["raw"] = raw_response
                except Exception:
                    out["parse_error"] = True
                    parts = []
                    if raw_response:
                        parts.append(raw_response)
                    if rc != 0:
                        parts.append(f"[codex_exit_code={rc}]")
                    if stderr_text:
                        parts.append(f"[stderr]\n{stderr_text}")
                    out["raw"] = "\n".join(parts).strip()

                fout.write(json.dumps(out, ensure_ascii=False) + "\n")
                processed += 1
                status = out.get("claim_verified", "parse_error" if out.get("parse_error") else "?")
                print(f"[{processed:02d}/{run_limit}] {rec['node_id']:20s} -> {status}")
                sys.stdout.flush()
    finally:
        schema_path.unlink(missing_ok=True)

    print("\n---SUMMARY---")
    print(f"processed={processed}")
    print(f"verified={verified['verified']}, plausible={verified['plausible']}, "
          f"gap={verified['gap']}, error={verified['error']}")
    print(f"output={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
